---
apiVersion: "skaffold/v1beta11"
kind: Config


profiles:
  - name: languagewire

    build:
      local:
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest"
      artifacts:

        - image: "gcr.io/technical-challenges/languagewire"
          context: .

    deploy:
      helm:

        flags:
          upgrade:
            - --install

        releases:

          - name: languagewire
            chartPath: helm/
            namespace: default
            valuesFiles:
              - "helm/values.yaml"
