---
apiVersion: "skaffold/v1beta15"
kind: Config


profiles:
  - name: languages

#    build:
#      local:
#        push: true
#      tagPolicy:
#        envTemplate:
#          template: "{{.IMAGE_NAME}}:latest"
#      artifacts:
#
#        - image: "loriin14/languages"
#          context: .

    deploy:
      helm:
        releases:
          - name: languagewire
            chartPath: helm/
            namespace: default
            valuesFiles:
              - "helm/values.yaml"
