apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicacount }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds | default 60 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.httpPort }}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
{{ if .Values.probes.useProbes }}
{{ toYaml .Values.probes.probesDefinitions | indent 8 }}
{{ end }}
