apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.autoScaling.maxReplicas }}
  behavior:
{{ toYaml .Values.autoScaling.behavior | indent 4 }}
  metrics:
{{ toYaml .Values.autoScaling.metrics | indent 4 }}

# TODO: scaledown issue when use "apiVersion: autoscaling/v2beta2"