apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
     app.kubernetes.io/name: {{ template "fullname" . }}
     app: languagewire-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
