---

deployment:
  image:
    pullPolicy: Always
    repository: 'loriin14/languages'
    tag: latest
  replicacount: 1
  resources:
    requests:
      memory: "120Mi"
      cpu: "250m"
    limits:
      memory: "150Mi"
      cpu: "500m"

service:
  httpPort: 5000

autoScaling:
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

probes:
  useProbes: true
  probesDefinitions:
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: http
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    startupProbe:
      httpGet:
        path: /
        port: http
      failureThreshold: 30
      periodSeconds: 5